name: macOS-Final
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Connect Pagekite
      run: |
        curl -s https://pagekite.net/pk/ | sudo python3
        python3 pagekite.py 5900 javi-mac.pagekite.me
